name: Release

on:
  push:
    branches: 
      - "*"
jobs:
  generate-cbom:
    uses: doowt/shared-workflows/.github/workflows/generate-cbom.yml@add-cbom-workflow
    permissions:
      security-events: write

  static-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/static-checks-npm.yml@main
    permissions:
      security-events: write
    with:
      matrix_commands: '["start"]'

  tests-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-npm.yml@main
    permissions:
      pull-requests: write
    with:
      docker_compose_file: ''
      npm_build_command: 'npm run start'
      tests: '["test:init"]'

  tests-e2e-npm:
    uses: digicatapult/shared-workflows/.github/workflows/tests-e2e-npm.yml@main
    permissions: {}
    with:
      docker_compose_file: ''
      pre_test_command: 'npm ci && npx playwright install-deps && npx playwright install'
      test_command: 'npm run test:playwright || exit 1'

  migration-checks-npm:
    uses: digicatapult/shared-workflows/.github/workflows/migration-checks-npm.yml@ENG-313-migration-checks
    permissions:
      contents: read
    with:
      seed_command: 'npm run db:seed'

  migration-checks-poetry:
    uses: digicatapult/shared-workflows/.github/workflows/migration-checks-poetry.yml@ENG-313-migration-checks
    permissions:
      contents: read

  build-docker:
    uses: digicatapult/shared-workflows/.github/workflows/build-docker.yml@main
    needs: [static-checks-npm, tests-npm, tests-e2e-npm, migration-checks-npm, migration-checks-poetry]
    permissions:
      contents: read
      packages: write
      security-events: write
    with:
      scan_container: true
      push_dockerhub: false
      push_ghcr: true
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.SQNC_DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.SQNC_DOCKERHUB_USERNAME }}

  generate-sbom-npm:
    uses: digicatapult/shared-workflows/.github/workflows/generate-sbom.yml@main
    permissions: {}
    needs: [build-docker]

  release-github:
    uses: digicatapult/shared-workflows/.github/workflows/release-github.yml@main
    permissions:
      contents: write
      pull-requests: read
    needs: [build-docker, generate-sbom-npm]
    with:
      get_sbom: true
    secrets: inherit
